### ISSUE TITLE
Use self-hosted runners with testground & libp2p/test-plan repo

### ISSUE THREAD

**Issue by laurentsenta** [pl-strflt/ipdx#38]
- [ ] install missing dependencies on the runner until we can build testground
- [ ] when we're done this might be an ideal time to document the workflow to install self-hosted runners in an org / repo (since we just done it).

**Comment by laurentsenta** [comment]
Getting close:
https://github.com/philips-labs/terraform-aws-github-runner/compare/develop...laurentsenta:feat/ipdx-testground-image

Built with:

```sh
packer build -var-file="./testground.pkrvars.hcl" .
packer build -var-file="./go1.18.pkrvars.hcl" .
```

It generates AMI like: `github-runner-ubuntu-focal-amd64-202206021224-testground`.

If you login with the AWS testground org, you can check them in https://eu-west-1.console.aws.amazon.com/ec2/v2/home?region=eu-west-1#Images:visibility=owned-by-me

We should be able to use them with something like:
https://github.com/pl-strflt/tf-aws-gh-runner/pull/1/files

Would it make sense to try merging this PR, to test that the AMI is picked up and everything works end to end,
before making it nice and reusable?

**Comment by galargh** [comment]
For anyone else following this issue, we're going to pair on this tomorrow. We'll update the issue with whatever we come up with together.

**Comment by laurentsenta** [comment]
Current state: We got the whole workflow running with custom AMIs, etc:
https://github.com/singulargarden/pl-github/actions/runs/2435526535

Left to do:

- [ ] tweak our setup so the testground test passes (see context deadline exceeded & go mod download errors)
- [ ] define "final" names & content for each of our AMIs

**Comment by aktech** [comment]
2 cents on self-hosting runners:

I built a service for running self-hosted GitHub Action runners on cloud with 0 maintenance and free for open source: https://cirun.io/

- It's on-demand, which means you only pay to your cloud provider for the time you're using it. It also supports arm based runners.
- All you need is a simple configuration .cirun.yml file, here is a [demo](https://www.youtube.com/watch?v=lDx0YVTn6yg).
- Also available on GitHub Marketplace as well: https://github.com/marketplace/cirun-io

**Comment by laurentsenta** [comment]
@galargh with stability improvements and TaaS getting closer, I'm going to close this, we can reopen it later, thanks for asking,
