### ISSUE TITLE
Remove duplicate annotations in Github Actions

### ISSUE THREAD

**Issue by laurentsenta** [pl-strflt/ipdx#40]
Raised by @marten-seemann in IPDX channel (https://filecoinproject.slack.com/archives/C03KLC57LKB/p1655660158017649)

This PR has one error,
https://github.com/libp2p/go-libp2p-resource-manager/pull/51/files
And gets 16 GitHub almost-identical annotations.

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/1136669/174991932-3b2ad3df-eec0-4e64-9d1a-8d51844ebed9.png">

Branch backup if we want to reproduce the error:
https://github.com/laurentsenta/go-libp2p-resource-manager/tree/marco/canonical-log-on-allowlist

**Comment by laurentsenta** [comment]
Notes from my investigations:

If you click on the view check run link on the right of the annotation, you'll end up with:

- go-test.yml on PR: https://github.com/libp2p/go-libp2p-resource-manager/actions/runs/2505492465
- go-test.yml on push: https://github.com/libp2p/go-libp2p-resource-manager/actions/runs/2505490060
- go-check,yml on push: https://github.com/libp2p/go-libp2p-resource-manager/actions/runs/2505490062

6 errors + 6 errors + 4 errors => 16 annotations.

---

There are a few open tickets related to deduping duplicate annotation in GitHub actions:

 - https://github.com/actions/toolkit/issues/395
 - https://github.com/actions/runner/issues/504
 - https://github.com/actions/runner/issues/264

---

We could avoid running the go-test.yml twice with:
https://github.com/marketplace/actions/skip-duplicate-actions and use the "Only skip same content" feature.

> **Only skip same content**: For example, this can be useful if a workflow has both a push and a pull_request trigger, or if you push a tag right after pushing a commit.

---

There is a comment about tee'ing output, and then using grep to dedup errors:
- https://github.com/actions/runner/issues/504#issuecomment-681874865

I guess we could use build artifacts to gather every build output, and then dedup'ing them in one final workflow.


---

Finally we might be able to create a dedup step using the github API:

```
# List all annotation checks for the commit
gh api '/repos/libp2p/go-libp2p-resource-manager/commits/a4731e99326c6b9a41d655046dd7f44bffaa311b/check-runs' | jq | less -R 

# List annotations for a check run
gh api '/repos/libp2p/go-libp2p-resource-manager/check-runs/6909149440/annotations'

# Update check runs
https://docs.github.com/en/rest/checks/runs#update-a-check-run
```

**Comment by laurentsenta** [comment]
I'm not sure how we should proceed:

- I couldn't find an obvious fix,
- We could dedup the "on pr" and "on push" events with the skip-duplicate actions, but from my naive understanding, you get the same result by trying to fix your pr and pushing again,
- Using the Github API to dedup annotations looks like the way to go, 

@galargh what do you think?

**Comment by galargh** [comment]
I agree that deduping using GitHub API seems like the only truly valid option here. The thing is though it would be quite time consuming. Because of this, I believe we should close this and only reopen if the report volume on this issue increases. Thank you for a thorough investigation 🙇
