### ISSUE TITLE
Add Status Date field to additional project boards

### ISSUE THREAD

**Issue by BigLep** [pl-strflt/ipdx#47]
Hi @ipdx,

I'd like to replicate adding a "Status Date" field like was done in https://github.com/protocol/w3dt-stewards/issues/43 but to do it for a couple of other boards:
- [x] https://github.com/orgs/libp2p/projects/3
- [x] https://github.com/orgs/ipld/projects/3

If it's self-service for me to enable this on other boards for the future let me know.  (If so it may be a good idea to have a "bells and whistles for GitHub projects" doc where could reference stuff like that so it's accessible).

Thanks,
Steve

Cc @p-shahi since we were also recently talking about this.

**Comment by p-shahi** [comment]
>If it's self-service for me to enable this on other boards for the future let me know. 

After digging around, I think it may be "semi" self-service. `Status Date` was shipped in https://github.com/ipfs/github-mgmt/pull/4 and we may be able to add it to [libp2p/github-mgmt](https://github.com/libp2p/github-mgmt) without too many hiccups 🤞 

The steps to do this are
- [ ] add `stale.yml` to `files/.github/workflows/`
- [ ] add `add-need-author-input-label-to-all-repositories.sh` to `scritps/`
- [ ] add `add-stale-workflow-to-all-repositories.sh` to `scripts/`
- [ ] add `.github/workflows/stale.yml` to appropriate repositories in `libp2p.yml`

@galargh does this seem right? I can take the task of adding this to libp2p if you and @BigLep are fine with it.

>If so it may be a good idea to have a "bells and whistles for GitHub projects" doc where could reference stuff like that so it's accessible)

+1 Might be a good idea to add to Notion

**Comment by BigLep** [comment]
@p-shahi : https://github.com/ipfs/github-mgmt/pull/4 looks to be about auto closing issues based on certain label and time conditions.

For this issue, I'm interested in adding a custom "Status Date" field to some boards (like was done for the Kubo board) and having it be autopopulated (as was done in https://github.com/protocol/w3dt-stewards/issues/43 ).

**Comment by p-shahi** [comment]
@BigLep D'oh I was digging into that discussion and went off on a tangent. 
But it looks like necessary steps to add `Status Date` and other metadata fields are provided here: https://github.com/pl-strflt/projects-status-history

**Comment by galargh** [comment]
Sorry I didn't get to it earlier. We sorted it out on Slack. But for the completness, for `Status Date` you have to:
1. Create fields in your chosen project as per https://github.com/pl-strflt/projects-status-history#project-status-history-timetamp-and-date-fields
1. Add your project to the include array in https://github.com/galargh/.github/blob/master/.github/workflows/update-status-history.yml#L14 (until it gets a better home, it lives in my private account)

**Comment by galargh** [comment]
Status Date field has not been added to both projects.
