### ISSUE TITLE
Migrate js-libp2p project board to new GitHub Projects

### ISSUE THREAD

**Issue by tinytb** [pl-strflt/ipdx#53]
https://github.com/orgs/libp2p/projects/2

Marin and Alex [noted](https://docs.google.com/document/d/1yWHlkyAlbwq4yXQtXU0Sifx4VtCyRoUoTk-I2lTpYTk/edit?usp=sharing) that the js-libp2p project board is a "classic" project and needs to be migrated to the new GitHub Projects. Steve indicated that IPDX helped to [migrate](https://github.com/protocol/w3dt-stewards/issues/39) go-ipfs, and that this `ipdx` repo is the new place for similar requests (the `w3dt-stewards` repo is not used for this purpose anymore).

Steve also suggested that, rather than just doing the migration for us, it may be more effective for IPDX to point me in the right direction (what steps should we take), so we can make this self-service for others.

**Comment by tinytb** [comment]
I found that GitHub has implemented [Project Migration](https://docs.github.com/en/issues/planning-and-tracking-with-projects/creating-projects/migrating-from-projects-classic) in [feature preview](https://docs.github.com/en/get-started/using-github/exploring-early-access-releases-with-feature-preview).

If no one is opposed, I will try out this feature today. @BigLep @mpetrunic @achingbrain @MarcoPolo

**Comment by tinytb** [comment]
The project has been migrated to here: https://github.com/orgs/libp2p/projects/5

Let me know if anyone notices any problems or inconveniences! @BigLep @mpetrunic @achingbrain @MarcoPolo

**Comment by BigLep** [comment]
Awesome - good to know - thanks!
