### ISSUE TITLE
IPDX Roadmap H1 2023

### ISSUE THREAD

**Issue by galargh** [pl-strflt/ipdx#67]
eta: 2023-08
description:
Visit the [notion page](https://www.notion.so/pl-strflt/IPDX-Roadmap-2023-21a7ca4ff0474d3fb764851d34a9e0b8) for detailed roadmap description, reasoning and context insights. **TLDR** The current team capacity allows us to maintain our current projects and [advance testground development](https://github.com/testground/testground/issues/1491) but we are not able to take on any other "big" initiatives 😿  

children:
- https://github.com/pl-strflt/ipdx/issues/68
- https://github.com/pl-strflt/ipdx/issues/69
- https://github.com/pl-strflt/ipdx/issues/70
- https://github.com/pl-strflt/ipdx/issues/71

**Comment by momack2** [comment]
Please add an ETA (ex just use eta: 2023Q2 or whatever quarter your roadmap plans up until so far)

**Comment by galargh** [comment]
This roadmap is now concluded. We've completed milestones 1-3 and moved milestone 4 to H2 roadmap - https://github.com/pl-strflt/ipdx/issues/81
