### ISSUE TITLE
Enable Secret Scanning with Push Protection in all PL repositories

### ISSUE THREAD

**Issue by galargh** [pl-strflt/ipdx#76]
We should do this via GitHub Management.

Ref https://www.notion.so/pl-strflt/Secret-Code-Scanning-w-Alain-e28db2eaa6e84465a98bac6ee063ceaf

**Comment by galargh** [comment]
Done! Example: https://github.com/ipfs/github-mgmt/pull/145

**Comment by BigLep** [comment]
@galargh : awesome - thanks for doing this.

Will this get enabled on new repos by default?

**Comment by galargh** [comment]
> Will this get enabled on new repos by default?

Yes! And if someone tries to disable it, then GitHub Management will propose reenabling it. Then we can follow up on such an event because I don't think we should disable it anywhere.
